### ISSUE TITLE
code for YDLIDAR-SDM15 in arduino ?

### ISSUE THREAD

**Issue by josh-001** [being24/YDLIDAR-SDM15_python#1]
I am working on YDLIDAR smd15 model ,could you please provide me code for to get distance from ydlidar using arduino?

**Comment by being24** [comment]
It is in this [repository](https://github.com/being24/YDLIDAR-SDM15_arduino) (the library is incomplete, so was kept private because I was too busy with research to complete it. It works well, at least on my robot).

Only ObtainVersionInfo, SelfCheckTest, StartScan, StopScan, GetScanData, and SetOutputFrequency are supported. It does not support all cmd's like the python version, such as changing the baud rate.

I plan to add the rest of the features to be implemented in the future.

For now, please use the python version for settings that cannot be done with the arduino version.

**Comment by josh-001** [comment]
Thank you for the code.
what are the libraries need to be installed for this particular ydlidar-sdm15 module?

**Comment by josh-001** [comment]
yeah, i got it 
i download the zip file and uploaded in the library manager.

**Comment by being24** [comment]
That's good.

When I finish the library, I will register it in arduinoIDE's library manager.

**Comment by josh-001** [comment]
That would be great :)
Thank you, the code is working in my system
